import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = [
    "product", "condition", "attr1Value", "attr2Value", "nameOverride",
    "attr1Sku", "attr2Sku", "skuManual", "sellingPrice",
    "skuPreview", "namePreview", "nameSourcePreview"
  ]

  static values = {
    products: Array,
    product: Object,
    conditions: Array
  }

  connect() {
    if (this.hasSellingPriceTarget && this.sellingPriceTarget.value.trim()) {
      this.sellingPriceTarget.dataset.autoGenerated = "true"
    }
    this.refresh()
  }

  markSkuManual() {
    if (this.hasSkuManualTarget) this.skuManualTarget.dataset.autoGenerated = "false"
  }

  markSellingPriceManual() {
    if (this.hasSellingPriceTarget) this.sellingPriceTarget.dataset.autoGenerated = "false"
  }

  refresh() {
    this.previewSku()
    this.previewSellingPrice()
    this.previewName()
  }

  selectedProduct() {
    if (this.hasProductValue && Object.keys(this.productValue).length > 0) {
      return this.productValue
    }
    if (!this.hasProductTarget) return null
    const id = parseInt(this.productTarget.value, 10)
    return this.productsValue.find((p) => p.id === id)
  }

  selectedCondition() {
    if (!this.hasConditionTarget || !this.conditionTarget.value) return null
    const id = parseInt(this.conditionTarget.value, 10)
    return this.conditionsValue.find((c) => c.id === id)
  }

  computedSku() {
    const product = this.selectedProduct()
    if (!product || !product.sku) return ""
    const condition = this.selectedCondition()
    const a1 = this.hasAttr1SkuTarget ? this.attr1SkuTarget.value.trim().toUpperCase() : ""
    const a2 = this.hasAttr2SkuTarget ? this.attr2SkuTarget.value.trim().toUpperCase() : ""
    const parts = []
    if (condition && condition.sku_component) parts.push(condition.sku_component)
    if (product.variation_type === "variable" && a1) parts.push(a1)
    if (product.variation_type === "matrix") {
      if (a1) parts.push(a1)
      if (a2) parts.push(a2)
    }
    return parts.length ? `${product.sku}-${parts.join("-")}` : product.sku
  }

  computedSellingPrice() {
    const product = this.selectedProduct()
    if (!product) return 0
    let price = product.list_price_cents || 0
    if (product.variation_type === "conditional") {
      const condition = this.selectedCondition()
      if (condition) {
        price = Math.floor(price * condition.default_list_price_factor_bps / 10000)
      }
    }
    return price
  }

  previewSku() {
    const sku = this.computedSku()
    if (this.hasSkuPreviewTarget) this.skuPreviewTarget.textContent = sku || "—"
  }

  previewSellingPrice() {
    if (!this.hasSellingPriceTarget || this.sellingPriceTarget.dataset.autoGenerated !== "true") return
    this.sellingPriceTarget.value = this.computedSellingPrice()
  }

  previewName() {
    if (!this.hasNamePreviewTarget) return
    const product = this.selectedProduct()
    if (!product) return

    const override = this.hasNameOverrideTarget ? this.nameOverrideTarget.value.trim() : ""
    if (override) {
      this.namePreviewTarget.textContent = override
      if (this.hasNameSourcePreviewTarget) this.nameSourcePreviewTarget.textContent = "Name override"
      return
    }

    const base = product.name || "—"
    const condition = this.selectedCondition()
    const a1 = this.hasAttr1ValueTarget ? this.attr1ValueTarget.value.trim() : ""
    const a2 = this.hasAttr2ValueTarget ? this.attr2ValueTarget.value.trim() : ""
    let name = base
    let source = "Product name"

    if (product.variation_type === "conditional" && condition && condition.short_name) {
      name = `${base} - ${condition.short_name}`
      source = "Product name + condition"
    } else if (product.variation_type === "variable" && a1) {
      name = `${base} - ${a1}`
      source = "Product name + attribute 1"
    } else if (product.variation_type === "matrix") {
      if (a1 && a2) {
        name = `${base} - ${a1} / ${a2}`
        source = "Product name + attributes 1 and 2"
      } else if (a1) {
        name = `${base} - ${a1}`
        source = "Product name + attribute 1"
      } else if (condition && condition.short_name) {
        name = `${base} - ${condition.short_name}`
        source = "Product name + condition"
      }
    }

    this.namePreviewTarget.textContent = name
    if (this.hasNameSourcePreviewTarget) this.nameSourcePreviewTarget.textContent = source
  }
}
